### ISSUE TITLE
Protege cannot parse file: org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=8:column=17] Expecting rdf:RDF element.

### ISSUE THREAD

**Issue by tschaffter** [allysonlister/swo#40]
Using Protege version 5.5.0, I can successfully open the file `swo_merged.owl` from the latest release ([SWO Release 1.6](https://github.com/allysonlister/swo/releases)).

However, the following error is thrown by Protege when trying to open either:

- https://github.com/allysonlister/swo/blob/master/release/1.6/swo_merged.owl
- https://github.com/allysonlister/swo/blob/master/release/swo.owl

![image](https://user-images.githubusercontent.com/3056480/69753835-5237fc00-1109-11ea-8517-15078a1e5f5c.png)

Error: `org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=8:column=17] Expecting rdf:RDF element.`

Stack Trace:

```
org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=8:column=17] Expecting rdf:RDF element.


Full Stack Trace
-----------------------------------------------------------------------------------------

org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFXMLParserException: org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=8:column=17] Expecting rdf:RDF element.
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:76)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:221)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1262)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1215)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1172)
	at org.protege.editor.owl.model.io.OntologyLoader.loadOntologyInternal(OntologyLoader.java:104)
	at org.protege.editor.owl.model.io.OntologyLoader.lambda$loadOntologyInOtherThread$0(OntologyLoader.java:62)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=8:column=17] Expecting rdf:RDF element.
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.verify(RDFParser.java:451)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.StartRDF.startElement(StartRDF.java:187)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.startElement(RDFParser.java:201)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:745)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3132)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:852)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.parse(RDFParser.java:145)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:73)
	... 10 more
```

**Comment by allysonlister** [comment]
Good morning! Apologies that you are having problems. We do actually have a newer release, but I haven't built a GitHub Release tag yet for it. 1.7 is the latest, and you can find it at https://github.com/allysonlister/swo/tree/master/release (In fact, you'll always be able to find the latest release files at that location.) There is also a README with details.

We made some big changes with 1.7 so please use that version. Please let me know if you have any issues with loading that version.

Additionally, I will make a "proper" release for GitHub and close this ticket when that's done. Thanks for pointing it out.

Thanks again, and best wishes,
Allyson

**Comment by allysonlister** [comment]
I've built a release, you can find it at https://github.com/allysonlister/swo/releases/tag/v1.7

thanks! Please let me know if you have any further questions.

:) Allyson

**Comment by tschaffter** [comment]
@allysonlister Thanks!

**Comment by Jad7171** [comment]
I have the same problem when I try to open my ontolog from URL? Do you have a procedure on step by step to solve this problem?

**Comment by Jad7171** [comment]
I have the same problem when I try to open my ontolog from URL? Do you have a procedure on step by step to solve this problem? I am trying to open from Ontology Online to my standalone Protege.
